name: Meu primeiro CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Compilar:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer git Clone
        uses: actions/checkout@v4

      - name: Hello World
        run: echo "hello, world!"

      - name: Java
        run: echo "Java!"

      - name: Executando dois
        run: |
          ls -l
          echo "Fim do processo"

    Docker:
     needs: Compilar
     runs-on: ubuntu-latest
    steps: 
     -name: Docker Login
   uses: docker/login-action@v4.6.0
  with:
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}

  -name: Build and push Docker images
  uses: docker/build-push-action@v7.4.0
  with:
   file: dockerfile
   push: true
   tags: caiodevone/gui-2faixa:1.0


